version: "3.9"

services:
  mysql-todo:
    container_name: 'database'
    image: mysql:5.7.22
    ports:
      - "3307:3306"
    expose:
      - "3307"
    environment:
      MYSQL_DATABASE: sapios
      MYSQL_ROOT_PASSWORD: senha

  api:
    build: .
    command: bash -c "npm run migrate && npm run seed && npm start" 
    ports:
      - "3000:3000"
    volumes: 
      - .:/usr/app
    depends_on:
      - mysql-todo

networks:
  default:
    driver: bridge
  

  
    

